bump_version: null
lint: null
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Friederike Hanssen, Susanne Jodoin
  description: Workflow converts one or multiple bam/cram files to fastq format
  force: false
  is_nfcore: true
  name: bamtofastq
  org: nf-core
  outdir: .
  skip_features:
    - multiqc
    - fastqc
  version: 2.1.2dev
update: null
